// International dialing codes. `iso` is the ISO-3166 alpha-2 code (used to render the
// flag emoji); `dial` is the country calling code (with leading +).
export interface Country {
  name: string;
  iso: string;
  dial: string;
}

/** Turn an ISO-3166 alpha-2 code into its flag emoji (regional indicator symbols). */
export function flagEmoji(iso: string): string {
  if (!iso || iso.length !== 2) return "🏳️";
  const base = 0x1f1e6;
  const cc = iso.toUpperCase();
  return String.fromCodePoint(
    base + (cc.charCodeAt(0) - 65),
    base + (cc.charCodeAt(1) - 65),
  );
}

export const COUNTRIES: Country[] = [
  { name: "Qatar", iso: "QA", dial: "+974" },
  { name: "Saudi Arabia", iso: "SA", dial: "+966" },
  { name: "United Arab Emirates", iso: "AE", dial: "+971" },
  { name: "Kuwait", iso: "KW", dial: "+965" },
  { name: "Bahrain", iso: "BH", dial: "+973" },
  { name: "Oman", iso: "OM", dial: "+968" },
  { name: "Egypt", iso: "EG", dial: "+20" },
  { name: "Jordan", iso: "JO", dial: "+962" },
  { name: "Lebanon", iso: "LB", dial: "+961" },
  { name: "Iraq", iso: "IQ", dial: "+964" },
  { name: "Syria", iso: "SY", dial: "+963" },
  { name: "Yemen", iso: "YE", dial: "+967" },
  { name: "Palestine", iso: "PS", dial: "+970" },
  { name: "Sudan", iso: "SD", dial: "+249" },
  { name: "Libya", iso: "LY", dial: "+218" },
  { name: "Tunisia", iso: "TN", dial: "+216" },
  { name: "Algeria", iso: "DZ", dial: "+213" },
  { name: "Morocco", iso: "MA", dial: "+212" },
  { name: "Mauritania", iso: "MR", dial: "+222" },
  { name: "India", iso: "IN", dial: "+91" },
  { name: "Pakistan", iso: "PK", dial: "+92" },
  { name: "Bangladesh", iso: "BD", dial: "+880" },
  { name: "Sri Lanka", iso: "LK", dial: "+94" },
  { name: "Nepal", iso: "NP", dial: "+977" },
  { name: "Philippines", iso: "PH", dial: "+63" },
  { name: "Indonesia", iso: "ID", dial: "+62" },
  { name: "Malaysia", iso: "MY", dial: "+60" },
  { name: "Singapore", iso: "SG", dial: "+65" },
  { name: "Thailand", iso: "TH", dial: "+66" },
  { name: "Vietnam", iso: "VN", dial: "+84" },
  { name: "China", iso: "CN", dial: "+86" },
  { name: "Hong Kong", iso: "HK", dial: "+852" },
  { name: "Japan", iso: "JP", dial: "+81" },
  { name: "South Korea", iso: "KR", dial: "+82" },
  { name: "Turkey", iso: "TR", dial: "+90" },
  { name: "Iran", iso: "IR", dial: "+98" },
  { name: "Afghanistan", iso: "AF", dial: "+93" },
  { name: "Kazakhstan", iso: "KZ", dial: "+7" },
  { name: "Uzbekistan", iso: "UZ", dial: "+998" },
  { name: "Azerbaijan", iso: "AZ", dial: "+994" },
  { name: "Georgia", iso: "GE", dial: "+995" },
  { name: "Armenia", iso: "AM", dial: "+374" },
  { name: "United Kingdom", iso: "GB", dial: "+44" },
  { name: "Ireland", iso: "IE", dial: "+353" },
  { name: "France", iso: "FR", dial: "+33" },
  { name: "Germany", iso: "DE", dial: "+49" },
  { name: "Spain", iso: "ES", dial: "+34" },
  { name: "Portugal", iso: "PT", dial: "+351" },
  { name: "Italy", iso: "IT", dial: "+39" },
  { name: "Netherlands", iso: "NL", dial: "+31" },
  { name: "Belgium", iso: "BE", dial: "+32" },
  { name: "Switzerland", iso: "CH", dial: "+41" },
  { name: "Austria", iso: "AT", dial: "+43" },
  { name: "Sweden", iso: "SE", dial: "+46" },
  { name: "Norway", iso: "NO", dial: "+47" },
  { name: "Denmark", iso: "DK", dial: "+45" },
  { name: "Finland", iso: "FI", dial: "+358" },
  { name: "Poland", iso: "PL", dial: "+48" },
  { name: "Czech Republic", iso: "CZ", dial: "+420" },
  { name: "Greece", iso: "GR", dial: "+30" },
  { name: "Romania", iso: "RO", dial: "+40" },
  { name: "Hungary", iso: "HU", dial: "+36" },
  { name: "Ukraine", iso: "UA", dial: "+380" },
  { name: "Russia", iso: "RU", dial: "+7" },
  { name: "United States", iso: "US", dial: "+1" },
  { name: "Canada", iso: "CA", dial: "+1" },
  { name: "Mexico", iso: "MX", dial: "+52" },
  { name: "Brazil", iso: "BR", dial: "+55" },
  { name: "Argentina", iso: "AR", dial: "+54" },
  { name: "Chile", iso: "CL", dial: "+56" },
  { name: "Colombia", iso: "CO", dial: "+57" },
  { name: "Peru", iso: "PE", dial: "+51" },
  { name: "Australia", iso: "AU", dial: "+61" },
  { name: "New Zealand", iso: "NZ", dial: "+64" },
  { name: "South Africa", iso: "ZA", dial: "+27" },
  { name: "Nigeria", iso: "NG", dial: "+234" },
  { name: "Kenya", iso: "KE", dial: "+254" },
  { name: "Ethiopia", iso: "ET", dial: "+251" },
  { name: "Ghana", iso: "GH", dial: "+233" },
  { name: "Tanzania", iso: "TZ", dial: "+255" },
  { name: "Uganda", iso: "UG", dial: "+256" },
  { name: "Somalia", iso: "SO", dial: "+252" },
  { name: "Djibouti", iso: "DJ", dial: "+253" },
  { name: "Cameroon", iso: "CM", dial: "+237" },
  { name: "Senegal", iso: "SN", dial: "+221" },
  { name: "Ivory Coast", iso: "CI", dial: "+225" },
  { name: "Bulgaria", iso: "BG", dial: "+359" },
  { name: "Croatia", iso: "HR", dial: "+385" },
  { name: "Serbia", iso: "RS", dial: "+381" },
  { name: "Slovakia", iso: "SK", dial: "+421" },
  { name: "Slovenia", iso: "SI", dial: "+386" },
  { name: "Lithuania", iso: "LT", dial: "+370" },
  { name: "Latvia", iso: "LV", dial: "+371" },
  { name: "Estonia", iso: "EE", dial: "+372" },
  { name: "Cyprus", iso: "CY", dial: "+357" },
  { name: "Malta", iso: "MT", dial: "+356" },
  { name: "Luxembourg", iso: "LU", dial: "+352" },
  { name: "Iceland", iso: "IS", dial: "+354" },
  { name: "Myanmar", iso: "MM", dial: "+95" },
  { name: "Cambodia", iso: "KH", dial: "+855" },
  { name: "Laos", iso: "LA", dial: "+856" },
  { name: "Mongolia", iso: "MN", dial: "+976" },
  { name: "Maldives", iso: "MV", dial: "+960" },
  { name: "Bhutan", iso: "BT", dial: "+975" },
  { name: "Brunei", iso: "BN", dial: "+673" },
  { name: "Taiwan", iso: "TW", dial: "+886" },
  { name: "Zambia", iso: "ZM", dial: "+260" },
  { name: "Zimbabwe", iso: "ZW", dial: "+263" },
  { name: "Angola", iso: "AO", dial: "+244" },
  { name: "Mozambique", iso: "MZ", dial: "+258" },
  { name: "Rwanda", iso: "RW", dial: "+250" },
  { name: "Madagascar", iso: "MG", dial: "+261" },
  { name: "Mali", iso: "ML", dial: "+223" },
  { name: "Burkina Faso", iso: "BF", dial: "+226" },
  { name: "Niger", iso: "NE", dial: "+227" },
  { name: "Chad", iso: "TD", dial: "+235" },
  { name: "Benin", iso: "BJ", dial: "+229" },
  { name: "Togo", iso: "TG", dial: "+228" },
  { name: "Gabon", iso: "GA", dial: "+241" },
  { name: "Congo", iso: "CG", dial: "+242" },
  { name: "DR Congo", iso: "CD", dial: "+243" },
  { name: "Tajikistan", iso: "TJ", dial: "+992" },
  { name: "Kyrgyzstan", iso: "KG", dial: "+996" },
  { name: "Turkmenistan", iso: "TM", dial: "+993" },
  { name: "Belarus", iso: "BY", dial: "+375" },
  { name: "Moldova", iso: "MD", dial: "+373" },
  { name: "Albania", iso: "AL", dial: "+355" },
  { name: "North Macedonia", iso: "MK", dial: "+389" },
  { name: "Bosnia and Herzegovina", iso: "BA", dial: "+387" },
  { name: "Montenegro", iso: "ME", dial: "+382" },
  { name: "Kosovo", iso: "XK", dial: "+383" },
];

export const DEFAULT_COUNTRY = COUNTRIES[0]; // Qatar
